version: 0.2

phases:
    pre_build:
        commands:
            ### Login to Amazon ECR
             - echo Logging in to Amazon ECR...
             - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/k1p5i4g9
    build:
        commands:
            ### Building the image 
             - echo Build started on `date`
             - docker build --file ./Backend.Dockerfile -t backend . 
             - docker tag backend:latest public.ecr.aws/k1p5i4g9/backend:latest
             - echo Build completed on `date`
    post_build:
        commands:
            ### Publish the docker image to ECR
            - echo Pushing the Docker image...
            - docker push public.ecr.aws/k1p5i4g9/backend:latest  
